USE hostelsync;

-- Seed data for HostelSync.
-- Password hashes below are placeholders for database testing only.
-- Replace them with hashes generated by your application's password-hashing library.

START TRANSACTION;

-- 1. Blocks
INSERT INTO blocks (id, block_name) VALUES
(1, 'A Block'),
(2, 'B Block'),
(3, 'C Block');

-- 2. Room types: one common type, as all rooms are treated alike.
INSERT INTO room_types (id, type_name, capacity) VALUES
(1, 'STANDARD', 3);

-- 3. Rooms
INSERT INTO rooms (id, room_number, block_id, room_type_id) VALUES
(1, 'A-101', 1, 1),
(2, 'A-102', 1, 1),
(3, 'A-103', 1, 1),
(4, 'B-101', 2, 1),
(5, 'B-102', 2, 1),
(6, 'C-101', 3, 1);

-- 4. Users
-- IDs 1-2 are admins; IDs 3-10 are boarders.
INSERT INTO users (id, name, email, password_hash, role, room_id) VALUES
(1, 'Hostel Admin One', 'admin1@hostelsync.test', 'HASH_PLACEHOLDER_ADMIN_1', 'ADMIN', NULL),
(2, 'Hostel Admin Two', 'admin2@hostelsync.test', 'HASH_PLACEHOLDER_ADMIN_2', 'ADMIN', NULL),
(3, 'Aarav Sharma', 'aarav@hostelsync.test', 'HASH_PLACEHOLDER_3', 'BOARDER', 1),
(4, 'Diya Das', 'diya@hostelsync.test', 'HASH_PLACEHOLDER_4', 'BOARDER', 1),
(5, 'Kabir Singh', 'kabir@hostelsync.test', 'HASH_PLACEHOLDER_5', 'BOARDER', 2),
(6, 'Mira Nath', 'mira@hostelsync.test', 'HASH_PLACEHOLDER_6', 'BOARDER', 3),
(7, 'Rohan Dutta', 'rohan@hostelsync.test', 'HASH_PLACEHOLDER_7', 'BOARDER', 4),
(8, 'Ananya Bora', 'ananya@hostelsync.test', 'HASH_PLACEHOLDER_8', 'BOARDER', 4),
(9, 'Ishaan Roy', 'ishaan@hostelsync.test', 'HASH_PLACEHOLDER_9', 'BOARDER', 5),
(10, 'Nisha Paul', 'nisha@hostelsync.test', 'HASH_PLACEHOLDER_10', 'BOARDER', NULL);

-- 5. Room swap requests
INSERT INTO room_swap_requests
(id, sender_id, receiver_id, admin_id, status) VALUES
(1, 3, 5, NULL, 'PENDING_B'),
(2, 6, 7, 1, 'PENDING_ADM'),
(3, 8, 9, 1, 'APPROVED'),
(4, 4, 6, 2, 'REJECTED');

-- 6. Mess rebates
INSERT INTO mess_rebates
(id, user_id, start_date, end_date, status, approved_by_id) VALUES
(1, 3, '2026-09-03', '2026-09-05', 'APPROVED', 1),
(2, 5, '2026-09-10', '2026-09-14', 'PENDING', NULL),
(3, 7, '2026-09-18', '2026-09-20', 'REJECTED', 2),
(4, 9, '2026-09-22', '2026-09-25', 'APPROVED', 1);

-- 7. Mess bills
INSERT INTO mess_bills
(id, user_id, bill_month, base_fee, rebate_amount, fine_amount, due_date, status) VALUES
(1, 3, '2026-09-01', 3000.00, 300.00, 0.00, '2026-10-10', 'UNPAID'),
(2, 4, '2026-09-01', 3000.00, 0.00, 0.00, '2026-10-10', 'UNPAID'),
(3, 5, '2026-09-01', 3000.00, 0.00, 0.00, '2026-10-10', 'UNPAID'),
(4, 6, '2026-09-01', 3000.00, 0.00, 100.00, '2026-09-20', 'UNPAID'),
(5, 7, '2026-09-01', 3000.00, 200.00, 0.00, '2026-10-10', 'UNPAID'),
(6, 8, '2026-09-01', 3000.00, 0.00, 0.00, '2026-10-10', 'PAID'),
(7, 9, '2026-09-01', 3000.00, 400.00, 0.00, '2026-10-10', 'UNPAID');

-- 8. Fee/fine details
INSERT INTO fee_fine_details
(id, bill_id, fine_amount, fine_date, fine_reason) VALUES
(1, 4, 100.00, '2026-09-25', 'Late payment fine');

-- 9. Payments
-- Illustrative references only; do not use as real payment IDs.
INSERT INTO payments
(id, payment_reference, user_id, bill_id, amount, status, verified_at, verified_by_id) VALUES
(1, 'TEST-TXN-10001', 8, 6, 3000.00, 'VERIFIED', '2026-09-28 12:00:00', 1),
(2, 'TEST-TXN-10002', 3, 1, 2700.00, 'PENDING', NULL, NULL),
(3, 'TEST-TXN-10003', 5, 3, 3000.00, 'FLAGGED', NULL, 2);

-- 10. Notices
INSERT INTO notices (id, admin_id, title, content) VALUES
(1, 1, 'Hostel Meeting', 'A hostel meeting will be held in the common room.'),
(2, 2, 'Water Supply Maintenance', 'Water supply may be interrupted during scheduled maintenance.');

-- 11. Events
INSERT INTO events (id, admin_id, title, description, event_date) VALUES
(1, 1, 'Hostel Orientation', 'Orientation for hostel residents.', '2026-10-05 16:00:00'),
(2, 2, 'Sports Evening', 'Inter-block sports activities.', '2026-10-12 17:30:00');

COMMIT;
